
development:
  adapter: postgresql
  encoding: unicode
  database: dinofinder_development
  pool: 5
  username: christopher
  password:
  timeout: 5000


test:
  adapter: postgresql
  encoding: unicode
  database: dinofinder_test
  pool: 5
  username: christopher
  password:
  timeout: 5000


